using System.Collections;
using UnityEngine;

public enum TileType {
	None = -1,
	Start = 0,
	End = 1,
	Straight = 3,
	Left = 4,
	Right = 5,
	Straight_Log = 6,
	Straight_River = 7,
	Landmark_Windmill = 8,
	Forest_Statue = 9,
	Straight_Slope_Down = 12,
	Landmark_Clocktower = 13,
	Straight_River_Crossing = 16,
	Straight_Slope = 17,
	Straight_Double = 18,
	Straight_Bezier = 19,
	Straight_River_Log_Crossing = 20,
	Checkpoint = 25,
	Opening = 26,
	Landmark_Evil_Tree = 27,
	Opening2 = 28,
	Opening3 = 29,
	Opening4 = 30,
	Opening5 = 31,
	Landmark_Fairy_Message = 32,
	Landmark_Broken_Bridge = 33,
	Landmark_Cemetery_Queen = 35,
	Landmark_Magic_Bridge = 36,
	Landmark_Tomb_Start = 37,
	Landmark_Tomb_Double = 38,
	Landmark_Tomb_Start_2 = 40,
	Landmark_Tomb_End = 41,
	Landmark_Cemetery_Coach = 42,
	Landmark_Graveyard = 43,
	Landmark_Graveyard_Start = 44,
	Landmark_Graveyard_End = 45,
	Landmark_Graveyard_Ghost = 46,
	Landmark_Graveyard_1 = 47,
	Landmark_Graveyard_2 = 48,
	Landmark_Graveyard_3 = 49,
	Landmark_Graveyard_4 = 50,
	Landmark_Graveyard_5 = 51,
	Landmark_Graveyard_6 = 52,
	Landmark_Graveyard_7 = 53,
	Landmark_Bog_Valley = 55,
	Landmark_Treasure_Key = 57,
	Landmark_Collapsing_Bridge = 58,
	Landmark_Goblin_Loot = 59,
	Landmark_Zipline = 61,
	Fairyland_Mushroom_Jump = 62,
	Fairyland_Goblin_Jump = 63,
	Fairyland_Pushed_Barrels = 64,
	Fairyland_Roasting_Pig = 65,
	Jungle_Pyramid = 66,
	Jungle_Valley_Start = 67,
	Jungle_Valley_1 = 68,
	Jungle_Valley_2 = 69,
	Jungle_Valley_End = 72,
	Jungle_Vortex = 73,
	Jungle_Enemy = 74,
	Mines_Torch = 75,
	Mines_Giant_Crystal = 76,
	Blizzard_Snow_Balls = 77,
	Blizzard_Avalanche = 78,
	Blizzard_Goblin_Jump = 79,
	Blizzard_Goblins_Valley = 80,
	Hell_Cerberus = 81,
	Hell_Cavern_Gibbets = 82,
	Hell_Bridge = 83,
	Hell_Banquet_Hall = 84,
	Hell_Drawbridge = 85,
	Hell_Pendulums = 86,
	Hell_Flame_Columns = 87,
	Hell_Demons = 88,
	Hell_Floor_Traps = 89,
	Blizzard_Before_End = 90,
	Blizzard_Refuge = 91,
	Blizzard_Dark_Queen_Calls_Storm = 92,
	Mines_Giant_Cave = 93,
	Forest_Burning_Bridge = 94,
	Forest_Magic_Mirror = 95,
	Cemetery_Endless_Graveyard_Start = 96,
	Jungle_Waterfall = 97,
	Teleport_Tx = 98,
	Teleport_Rx = 99,
	Jump_Pad = 100,
	Finish_Line = 101,
	Angled = 103,
	Original_1 = 104,
	Original_2 = 105,
	Original_3 = 106

}

public enum TileSubType {
	None = -1,
	Straight = 3,
	Left = 4,
	Right = 5
}

public class TileTypes {

	
}
